# Generated by Django 4.2.1 on 2023-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoice", "0002_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
